[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://nkzrjkzuhpwadvsbfuea.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5renJqa3p1aHB3YWR2c2JmdWVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTExNjM0NzMsImV4cCI6MjEwNjczOTQ3M30.Cxc_P92UNzhsH1BIxF9fZgoXV4pyNtvuna8Xp9Lde-Y"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
